apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sjwoodr/blackhawks-facts
  newTag: latest

nameSuffix: -development

namespace: default

commonLabels:
  app: blackhawks-facts-development

resources:
- ../base
