apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sjwoodr/blackhawks-facts
  newTag: latest

nameSuffix: -staging

namespace: staging

commonLabels:
  app: blackhawks-facts-staging

resources:
- ../base
