apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sjwoodr/blackhawks-facts
  newTag: latest

nameSuffix: -staging

#namespace: staging

commonLabels:
  app: blackhawks-facts-staging

resources:
- ../base
- virtualsvc.yaml
#- ingress.yaml

# we'll only set the namespace to staging if its not already being set
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: staging
    unsetOnly: true
